In [1]:
import numpy as np

In [2]:
# image
"""
0 1 4 1 5 9 0
3 2 4 1 1 9 2
3 3 2 1 3 0 2 
0 1 0 3 5 9 2
3 1 1 1 0 0 2
3 2 2 1 5 1 2
7 1 4 1 5 9 1
"""

# filter 
"""
3 1 1 4 5
1 2 0 3 0
0 1 3 0 3
1 0 1 1 0
2 3 0 3 1
"""

image = np.array([  [0, 1, 4, 1, 5, 9, 0], 
                    [3, 2, 4, 1, 1, 9, 2], 
                    [3, 3, 2, 1, 3, 0, 2], 
                    [0, 1, 0, 3, 5, 9, 2], 
                    [3, 1, 1, 1, 0, 0, 2], 
                    [3, 2, 2, 1, 5, 1, 2], 
                    [7, 1, 4, 1, 5, 9, 1] ]) 

filter = np.array([ [3, 1, 1, 4, 5],
                    [1, 2, 0, 3, 0],
                    [0, 1, 3, 0, 3],
                    [1, 0, 1, 1, 0],
                    [2, 3, 0, 3, 1] ])

In [3]:
def filter_calculation(image, filter):
    # Zero padding
    padded_image = np.pad(image, ((2, 2), (2, 2)), mode='constant')

    # Initialize output arrays
    convolved = np.zeros_like(image)
    correlated = np.zeros_like(image)

    print("Padded image:\n" , padded_image)
    print("-" * 50)

    # Flip filter for convolution
    flipped_filter = np.flip(filter)

    # Apply convolution and correlation
    for i in range(2, padded_image.shape[0] - 2):
        for j in range(2, padded_image.shape[1] - 2):
            convolved[i-2, j-2] = np.sum(padded_image[i-2:i+3, j-2:j+3] * flipped_filter)
            correlated[i-2, j-2] = np.sum(padded_image[i-2:i+3, j-2:j+3] * filter)

            # Print full calculation for the first line
            if i >= 2:
                print("Convolution for pixel ({}, {}):".format(i-2, j-2))
                print("Image block:\n", padded_image[i-2:i+3, j-2:j+3])
                print("Flipped filter:\n", flipped_filter)
                print("Multiplication:\n", padded_image[i-2:i+3, j-2:j+3] * flipped_filter)
                print("Sum: ", convolved[i-2, j-2])
                print()

                print("Correlation for pixel ({}, {}):".format(i-2, j-2))
                print("Image block:\n", padded_image[i-2:i+3, j-2:j+3])
                print("Filter:\n", filter)
                print("Multiplication:\n", padded_image[i-2:i+3, j-2:j+3] * filter)
                print("Sum: ", correlated[i-2, j-2])
                print()


    return convolved, correlated

In [4]:
# Set print options
np.set_printoptions(threshold=np.inf, linewidth=np.inf, edgeitems=np.inf)

print("-" * 50)
convolved, correlated = filter_calculation(image, filter)
print("-" * 50)
print("Convolved Image")
print(convolved)
print("-" * 50)
print("Correlated Image")
print(correlated)

--------------------------------------------------
Padded image:
 [[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 4 1 5 9 0 0 0]
 [0 0 3 2 4 1 1 9 2 0 0]
 [0 0 3 3 2 1 3 0 2 0 0]
 [0 0 0 1 0 3 5 9 2 0 0]
 [0 0 3 1 1 1 0 0 2 0 0]
 [0 0 3 2 2 1 5 1 2 0 0]
 [0 0 7 1 4 1 5 9 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
--------------------------------------------------
Convolution for pixel (0, 0):
Image block:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 4]
 [0 0 3 2 4]
 [0 0 3 3 2]]
Flipped filter:
 [[1 3 0 3 2]
 [0 1 1 0 1]
 [3 0 3 1 0]
 [0 3 0 2 1]
 [5 4 1 1 3]]
Multiplication:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 4 4]
 [0 0 3 3 6]]
Sum:  21

Correlation for pixel (0, 0):
Image block:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 4]
 [0 0 3 2 4]
 [0 0 3 3 2]]
Filter:
 [[3 1 1 4 5]
 [1 2 0 3 0]
 [0 1 3 0 3]
 [1 0 1 1 0]
 [2 3 0 3 1]]
Multiplication:
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 12]
 [ 0  0  3  2  0]
 [ 0  0  0  9  2]]
Sum:  28

Convolution for pi

In [5]:
import pandas as pd

# Define the 4x4 image
img = np.array([[4, 12, 15, 1], [14, 0, 9, 2], [3, 7, 8, 13], [1, 0, 10, 11]])

# Convert the numbers to binary format
binary_img = np.vectorize("{:08b}".format)(img)

# Display the binary image
binary_df = pd.DataFrame(binary_img)
print("Binary Image:")
print(binary_df)

# Extract and print all 8 bit planes
for k in range(8):
    bit_plane = (img & (1 << k)) >> k
    print(f'\nBit plane {k}:')
    print(pd.DataFrame(bit_plane))

Binary Image:
          0         1         2         3
0  00000100  00001100  00001111  00000001
1  00001110  00000000  00001001  00000010
2  00000011  00000111  00001000  00001101
3  00000001  00000000  00001010  00001011

Bit plane 0:
   0  1  2  3
0  0  0  1  1
1  0  0  1  0
2  1  1  0  1
3  1  0  0  1

Bit plane 1:
   0  1  2  3
0  0  0  1  0
1  1  0  0  1
2  1  1  0  0
3  0  0  1  1

Bit plane 2:
   0  1  2  3
0  1  1  1  0
1  1  0  0  0
2  0  1  0  1
3  0  0  0  0

Bit plane 3:
   0  1  2  3
0  0  1  1  0
1  1  0  1  0
2  0  0  1  1
3  0  0  1  1

Bit plane 4:
   0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0

Bit plane 5:
   0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0

Bit plane 6:
   0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0

Bit plane 7:
   0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  0  0  0
3  0  0  0  0
